CREATE TABLE `news_data_all` (
  `id` varchar(40) NOT NULL,
  `news_date` date NOT NULL,
  `media_name` varchar(50) NOT NULL,
  `writer` varchar(120) NOT NULL,
  `title` varchar(200) NOT NULL,
  `key1` varchar(100) DEFAULT NULL,
  `key2` varchar(100) DEFAULT NULL,
  `key3` varchar(100) DEFAULT NULL,
  `acident1` varchar(100) DEFAULT NULL,
  `acident2` varchar(100) DEFAULT NULL,
  `acident3` varchar(100) DEFAULT NULL,
  `character` varchar(500) DEFAULT NULL,
  `location` varchar(200) DEFAULT NULL,
  `agency` varchar(500) DEFAULT NULL,
  `keyword` varchar(5000) DEFAULT NULL,
  `keyword_export` varchar(500) DEFAULT NULL,
  `sentence` varchar(500) DEFAULT NULL,
  `url` varchar(300) DEFAULT NULL,
  `body` longtext,
  `exception` varchar(45) DEFAULT NULL,
  `duplication` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
