CREATE TABLE `news_data` (
  `id` varchar(40) NOT NULL,
  `news_date` date DEFAULT NULL,
  `media_name` varchar(50) DEFAULT NULL,
  `writer` varchar(120) DEFAULT NULL,
  `title` varchar(200) DEFAULT NULL,
  `key1` varchar(100) DEFAULT NULL,
  `key2` varchar(100) DEFAULT NULL,
  `key3` varchar(100) DEFAULT NULL,
  `acident1` varchar(100) DEFAULT NULL,
  `acident2` varchar(100) DEFAULT NULL,
  `acident3` varchar(100) DEFAULT NULL,
  `character` varchar(1000) DEFAULT NULL,
  `location` varchar(200) DEFAULT NULL,
  `agency` varchar(500) DEFAULT NULL,
  `keyword` varchar(10000) DEFAULT NULL,
  `keyword_export` varchar(2500) DEFAULT NULL,
  `url` varchar(300) DEFAULT NULL,
  `body` longtext,
  `exception` varchar(45) DEFAULT NULL,
  `valid` int(11) DEFAULT NULL,
  `value` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;